model: 'densenet169' # alexnet resnet50 densenet169
epoch: 50 # 20 30 50
lr: 0.001 # 0.001 0.0005 0.0001
batch_size: 64 # 64 128
label_smooth: 0.1
warmup_epoch: 1
val_interval: 1
data_root: "/workspace/data/cls_1207_data/5-FourBall-Continuous-20-03-15_Single-1"
train_txt: "/workspace/data/cls_1207_data/pose_train.txt"
val_txt: "/workspace/data/cls_1207_data/pose_val.txt"
num_classes: 36 # 36 72